# Generated by Django 5.2 on 2026-03-31 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_options_appointment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='0,1,2,3,4', max_length=32),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='slot_duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='workday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='workday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
