# Generated by Django 5.2 on 2026-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
