# Generated by Django 5.2 on 2026-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegramlinkcode_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
