# Generated by Django 5.2 on 2026-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_archived_at_appointment_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_day_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_day_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
